
###############CASO ALUMNO#######################
GET http://192.168.18.92:4567/curso/alumno
    ?usuario_id=3

###############CASO PROFESOR#####################
GET http://192.168.18.92:4567/curso/profesor
    ?usuario_id=1