#############################################
GET http://192.168.1.22:4567/member/exercise
  ?member_id=1
  &exercise_id=53

#############################################
GET http://192.168.1.22:4567/member/resume
  ?member_id=1

#############################################
GET http://192.168.1.22:4567/member/exercises
  ?member_id=1