#############################################
GET http://127.0.0.1:4567/qr/profesor
  ?profesor_id=2

#############################################
GET http://127.0.0.1:4567/qr/alumno
  ?sesion_id=10
  &alumno_id=3
